import fs from "fs";
import path from "path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import * as schema from "./schema.js";

// Resolved against process.cwd(), which npm workspaces sets to server/ for
// both `npm run dev -w server` (tsx) and `npm run start` (node dist/index.js).
const dataDir = path.resolve(process.cwd(), "data");
fs.mkdirSync(dataDir, { recursive: true });
const dbPath = path.join(dataDir, "timeblocker.db");

const sqlite = new Database(dbPath);
sqlite.pragma("journal_mode = WAL");
sqlite.pragma("foreign_keys = ON");

export const db = drizzle(sqlite, { schema });

// Migrations are plain .sql files generated by `npm run db:generate` and
// checked into git — applying them here means a fresh checkout just works.
migrate(db, { migrationsFolder: path.resolve(process.cwd(), "drizzle") });
